MvcOnlineTicariOtomasyon/Models/Siniflar/Departman.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Siniflar
{
    public class Departman
    {
        [Key]
        public int DepartmanID { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(30, ErrorMessage = "En fazla 30 karakter giriniz")]
        [Required(ErrorMessage = "Bu alanı boş geçmeyin")]
        public string DepartmanAd { get; set; }

        public bool Durum { get; set; }
        public ICollection<Personel> Personels { get; set; }
    }
}

MvcOnlineTicariOtomasyon/Controllers/DepartmanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class DepartmanController : Controller
    {
        // GET: Departman
        Context c = new Context();
        
        public ActionResult Index()
        {
            var degerler = c.Departmens.Where(x => x.Durum == true).ToList();
            return View(degerler);
        }
        [Authorize(Roles = "A")]
        [HttpGet]
        public ActionResult DepartmanEkle()
        {
            return View();
        }

        [HttpPost]
        public ActionResult DepartmanEkle(Departman d)
        {
            c.Departmens.Add(d);
            c.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DepartmanSil(int id)
        {
            var sil = c.Departmens.Find(id);
            sil.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");

        }
        public ActionResult DepartmanGetir(int id)
        {
            var departman = c.Departmens.Find(id);
            return View("DepartmanGetir",departman);
        }
        public ActionResult DepartmanGuncelle(Departman d)
        {
            var dprtmn = c.Departmens.Find(d.DepartmanID);
            dprtmn.DepartmanAd = d.DepartmanAd;
            dprtmn.Durum = d.Durum;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DepartmanDetay(int id)
        {
            var detay = c.Personels.Where(x=>x.departmanid==id).ToList();
            var dprtm = c.Departmens.Where(x => x.DepartmanID == id).Select(y => y.DepartmanAd).FirstOrDefault();
            ViewBag.dpr = dprtm;
            return View(detay);
        }
        public ActionResult DepartmanPersonelSatis(int id)
        {
            var detay = c.SatisHarekets.Where(x => x.Personelid == id).ToList();
            var prsnl = c.Personels.Where(x => x.PersonelID == id).Select(y => y.PersonelAd + " "+ y.PersonelSoyad).FirstOrDefault();
            ViewBag.prs = prsnl;
            return View(detay);
        }

    }
}

MvcOnlineTicariOtomasyon/Views/Departman/DepartmanDetay.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Personel>
@{
    ViewBag.Title = "DepartmanDetay";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />

<h2>Departman Detayı</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">@ViewBag.dpr Departmanı Personelleri</li>
</ol>

<table class="table table-hover">
    <tr>
        <th>PersonelID</th>
        <th>Adı</th>
        <th>Soyadı</th>
        <th>Görsel</th>
        <th>Satışlar</th>
    </tr>
    @foreach (var x in Model)
    {
<tr>
    <td>@x.PersonelID</td>
    <td>@x.PersonelAd</td>
    <td>@x.PersonelSoyad</td>
    <td>
        <img src="@x.PersonelGorsel" style="width:80px;height:60px;" />
    </td>
    <td><a href="/Departman/DepartmanPersonelSatis/@x.PersonelID" class="btn btn-primary">Yapılan Satışlar</a></td>

</tr>
    }

</table>

MvcOnlineTicariOtomasyon/Views/Departman/DepartmanEkle.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Departman
@{
    ViewBag.Title = "DepartmanEkle";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departman Ekle</h2>
<br />

<form class="form-group" method="post">
    @Html.LabelFor(x=>x.DepartmanAd)
    @Html.TextBoxFor(x=>x.DepartmanAd, new {@class="form-control" })
    <br />
    <button class="btn btn-info">Departman Ekle</button>

</form>

MvcOnlineTicariOtomasyon/Views/Departman/DepartmanGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Departman
@{
    ViewBag.Title = "DepartmanGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departman'ı Güncelle</h2>

@using(Html.BeginForm("DepartmanGuncelle", "Departman", FormMethod.Post))
{
    <div class="form-group">
        @Html.HiddenFor(x=>x.DepartmanID)
        <br />
        @Html.LabelFor(x=>x.DepartmanAd)
        @Html.TextBoxFor(x=>x.DepartmanAd, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Durum)
        @Html.TextBoxFor(x => x.Durum, new { @class = "form-control" })
        <br />
        <button class="btn btn-warning">Güncelle</button>

    </div>
}

MvcOnlineTicariOtomasyon/Views/Departman/DepartmanPersonelSatis.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "DepartmanPersonelSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Personelin Yaptığı Satışlar</h2>

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Personel : @ViewBag.prs</li>
</ol>
<table class="table table-condensed">
    <tr>
        <th>Satış ID</th>
        <th>Ürün</th>
        <th>Müşteri</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>
    @foreach(var p in Model)
    {
        <tr>
            <td>@p.SatisID</td>
            <td>@p.Urun.UrunAd</td>
            <td>@p.Cariler.CariAd @p.Cariler.CariSoyad</td>
            <td>@p.Fiyat</td>
            <td>@p.Adet</td>
            <td>@p.ToplamTutar</td>
            <td>@p.Tarih</td>
            <td><a href="/Satis/SatisYazdir/@p.SatisID" class="btn btn-default" style="background-color:dodgerblue">Yazdır</a></td>
        </tr>
    }
</table>

MvcOnlineTicariOtomasyon/Views/Departman/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Departman>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Departmanlar</h2>
<table class="table table-condensed">
    <tr>
        <th>ID</th>
        <th>Departman Adı</th>
        <th>Guncelle</th>
        <th>Sil</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var x in Model)
    {
<tr>
    <td>@x.DepartmanID</td>
    <td>@x.DepartmanAd</td>
    <td><a href="/Departman/DepartmanGetir/@x.DepartmanID" class="btn btn-success">Güncelle</a></td>
    <td><a href="/Departman/DepartmanSil/@x.DepartmanID" class="btn btn-danger">Sil</a></td>
    <td><a href="/Departman/DepartmanDetay/@x.DepartmanID" class="btn btn-info">Detaylar</a></td>

</tr>
    }

</table>
<a href="/Departman/DepartmanEkle/" class="btn btn-primary">Yeni Departman Ekle</a>