MvcOnlineTicariOtomasyon/Controllers/SatisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers
{

    public class SatisController : Controller
    {
        // GET: Satis
        Context c = new Context();
        public ActionResult Index()
        {
            var deger = c.SatisHarekets.ToList();
            return View(deger);
        }
        [HttpGet]
        public ActionResult YeniSatis()
        {
            List<SelectListItem> deger1 = (from x in c.Uruns.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.UrunID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            List<SelectListItem> deger2 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " "+ x.PersonelSoyad,
                                               Value = x.PersonelID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;
            List<SelectListItem> deger3 = (from x in c.Carilers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + " "+ x.CariSoyad,
                                               Value = x.CariID.ToString()
                                           }).ToList();
            ViewBag.dgr3 = deger3;
            return View();
        }
        public ActionResult YeniSatis(SatisHareket s)
        {
            c.SatisHarekets.Add(s);
            s.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SatisGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Uruns.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.UrunAd,
                                               Value = x.UrunID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            List<SelectListItem> deger2 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.PersonelID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;
            List<SelectListItem> deger3 = (from x in c.Carilers.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.CariAd + " " + x.CariSoyad,
                                               Value = x.CariID.ToString()
                                           }).ToList();
            ViewBag.dgr3 = deger3;

            var satis = c.SatisHarekets.Find(id);
            return View("SatisGetir",satis);
        }
        public ActionResult SatisGuncelle(SatisHareket sa)
        {
            var satisg = c.SatisHarekets.Find(sa.SatisID);
            satisg.Urunid = sa.Urunid;
            satisg.Personelid = sa.Personelid;
            satisg.Cariid = sa.Cariid;
            satisg.Fiyat = sa.Fiyat;
            satisg.Adet = sa.Adet;
            satisg.ToplamTutar = sa.ToplamTutar;
            satisg.Tarih = sa.Tarih;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult SatisYazdir(int id)
        {
            var deger = c.SatisHarekets.Where(x => x.SatisID == id).ToList();
            return View(deger);
        }
        public ActionResult HepsiniYazdir()
        {
            var degerim = c.SatisHarekets.ToList();
            return View(degerim);
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Satis/HepsiniYazdir.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    Layout = null;
}

<h2>Satis PDF</h2>

<!DOCTYPE html>

<html lang="tr">

<head>

    <meta charset="UTF-8">

    <title>Bootstrap 4 Responsive Datatable and Export to PDF, CSV</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">

</head>

<body>

    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">

        <thead>

            <tr>

                <th>Satış ID</th>
                <th>Ürün</th>
                <th>Satan Personel</th>
                <th>Ürünü Alan</th>
                <th>Fiyat</th>
                <th>Adet</th>
                <th>Toplam</th>
                <th>Tarih</th>

            </tr>

        </thead>

        <tbody>


            @foreach (var x in Model)
            {
                <tr>
                    <td>@x.SatisID</td>
                    <td>@x.Urun.UrunAd</td>
                    <td>@x.Personel.PersonelAd @x.Personel.PersonelSoyad</td>
                    <td>@x.Cariler.CariAd @x.Cariler.CariSoyad</td>
                    <td>@x.Fiyat</td>
                    <td>@x.Adet</td>
                    <td>@x.ToplamTutar</td>
                    <td>@x.Tarih</td>
                </tr>
            }

        </tbody>

    </table>

    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>

    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>

    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>

    <script>

        $(document).ready(function () {

            var table = $('#example').DataTable({

                lengthChange: false,

                buttons: ['copy', 'excel', 'csv', 'pdf', 'colvis']

            });



            table.buttons().container()

                .appendTo('#example_wrapper .col-md-6:eq(0)');

        });

    </script>

</body>

</html>

MvcOnlineTicariOtomasyon/Views/Satis/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Yapılan Satişlar</h2>
<a href="/Satis/HepsiniYazdir/" class="btn btn-default" style="background-color:dodgerblue">Hepsini Yazdır</a>
<br />
<br />
<table id="tablo1" class="table table-hover">
    
    <thead>
        
        <tr>
            <th>Satış ID</th>
            <th>Ürün</th>
            <th>Satan Personel</th>
            <th>Ürünü Alan</th>
            <th>Fiyat</th>
            <th>Adet</th>
            <th>Toplam</th>
            <th>Tarih</th>
            <th>Güncelle</th>
            <th>Yazdır</th>
        </tr>
    </thead>

    @foreach (var x in Model)
    {
        <tr>
            <td>@x.SatisID</td>
            <td>@x.Urun.UrunAd</td>
            <td>@x.Personel.PersonelAd @x.Personel.PersonelSoyad</td>
            <td>@x.Cariler.CariAd @x.Cariler.CariSoyad</td>
            <td>@x.Fiyat</td>
            <td>@x.Adet</td>
            <td>@x.ToplamTutar</td>
            <td>@x.Tarih</td>
            <td><a href="/Satis/SatisGetir/@x.SatisID" class="btn btn-success">Güncelle</a></td>
            <td><a href="/Satis/SatisYazdir/@x.SatisID" class="btn btn-default" style="background-color:dodgerblue">Yazdır</a></td>
        </tr>
    }
</table>
<a href="/Satis/YeniSatis/" class="btn btn-primary">Yeni Satış Ekle</a>

@*<link href="~/Content/bootstrap.css" rel="stylesheet" />*@
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>

<link href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap.min.css" rel="stylesheet" />
<link href="https://cdn.datatables.net/responsive/2.1.1/css/responsive.bootstrap.min.css" rel="stylesheet" />
<script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js "></script>

<script>
    $('#tablo1').dataTable({});
</script>

MvcOnlineTicariOtomasyon/Views/Satis/SatisGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "SatisGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Yapılan Satışı Güncelle</h2>
@using(Html.BeginForm("SatisGuncelle", "Satis", FormMethod.Post))
{
<div class="form-group">
    @Html.HiddenFor(x => x.SatisID)
    @Html.LabelFor(x=>x.Urun)
    @Html.DropDownListFor(x=>x.Urunid, (List<SelectListItem>)ViewBag.dgr1, new { @class="form-control"})
    <br />
    @Html.LabelFor(x=>x.Personel)
    @Html.DropDownListFor(x=>x.Personelid, (List<SelectListItem>)ViewBag.dgr2, new { @class="form-control"})
    <br />
    @Html.LabelFor(x=>x.Cariler)
    @Html.DropDownListFor(x=>x.Cariid, (List<SelectListItem>)ViewBag.dgr3, new { @class="form-control"})
    <br />
    @Html.LabelFor(x=>x.Fiyat)
    @Html.TextBoxFor(x=>x.Fiyat, new { @class="form-control"})
    <br />
    @Html.LabelFor(x=>x.Adet)
    @Html.TextBoxFor(x=>x.Adet, new { @class="form-control" })
    <br />
    @Html.LabelFor(x=>x.ToplamTutar)
    @Html.TextBoxFor(x=>x.ToplamTutar, new { @class="form-control" })
    <br />
    @Html.LabelFor(x=>x.Tarih)
    @Html.TextBoxFor(x=>x.Tarih, new { @class="form-control" })
    <br />
    <button class="btn btn-warning">Güncelle</button>

</div>


}

MvcOnlineTicariOtomasyon/Views/Satis/SatisYazdir.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<SatisHareket>
@{
    Layout = null;
}

<h2>Satis PDF</h2>

<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>Bootstrap 4 Responsive Datatable and Export to PDF, CSV</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">

    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">

</head>

<body>

    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">

        <thead>

            <tr>

                <th>Satış ID</th>
                <th>Ürün</th>
                <th>Satan Personel</th>
                <th>Ürünü Alan</th>
                <th>Fiyat</th>
                <th>Adet</th>
                <th>Toplam</th>
                <th>Tarih</th>

            </tr>

        </thead>

        <tbody>


        @foreach (var x in Model)
        {
            <tr>
                <td>@x.SatisID</td>
                <td>@x.Urun.UrunAd</td>
                <td>@x.Personel.PersonelAd @x.Personel.PersonelSoyad</td>
                <td>@x.Cariler.CariAd @x.Cariler.CariSoyad</td>
                <td>@x.Fiyat</td>
                <td>@x.Adet</td>
                <td>@x.ToplamTutar</td>
                <td>@x.Tarih</td>
            </tr>
        }

    </tbody>

    </table>

    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>

    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>

    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>

    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>

    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>

    <script>

        $(document).ready(function () {

            var table = $('#example').DataTable({

                lengthChange: false,

                buttons: ['copy', 'excel', 'csv', 'pdf', 'colvis']

            });



            table.buttons().container()

                .appendTo('#example_wrapper .col-md-6:eq(0)');

        });

    </script>

</body>

</html>

MvcOnlineTicariOtomasyon/Views/Satis/YeniSatis.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.SatisHareket
@{
    ViewBag.Title = "YeniSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Yeni Satis Formu</h2>

<form class="form-group" method="post">
    @Html.LabelFor(x => x.Urun)
    @Html.DropDownListFor(x=>x.Urunid, (List<SelectListItem>)ViewBag.dgr1, new { @class="form-control"})
    <br />
    @Html.LabelFor(x => x.Personel)
    @Html.DropDownListFor(x=>x.Personelid, (List<SelectListItem>)ViewBag.dgr2, new { @class="form-control"})
    <br />
    @Html.LabelFor(x => x.Cariler)
    @Html.DropDownListFor(x=>x.Cariid, (List<SelectListItem>)ViewBag.dgr3, new { @class="form-control"})
    <br />
    @Html.LabelFor(x => x.Fiyat)
    @Html.TextBoxFor(x => x.Fiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x=>x.Adet)
    @Html.TextBoxFor(x=>x.Adet, new { @class="form-control" })
    <br />
    @Html.LabelFor(x=>x.ToplamTutar)
    @Html.TextBoxFor(x=>x.ToplamTutar, new { @class="form-control" })
    <br />
    <button class="btn btn-info">Yeni Satış Ekle</button>
</form>