MvcOnlineTicariOtomasyon/Models/Siniflar/KargoTakip.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Siniflar
{
    public class KargoTakip
    {
        [Key]
        public int KargoTakipid { get; set; }

        [Column(TypeName ="Varchar")]
        [StringLength(10, ErrorMessage = "En fazla 10 karakter giriniz")]
        public string TakipKodu { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(250, ErrorMessage = "En fazla 250 karakter giriniz")]
        public string Aciklama { get; set; }
        public DateTime TarihZaman { get; set; }
    }
}

MvcOnlineTicariOtomasyon/Controllers/KargoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class KargoController : Controller
    {
        // GET: Kargo
        Context c = new Context();
        public ActionResult Index(string kod)
        {
            var takip = from x in c.KargoDetays select x;
            if (!string.IsNullOrEmpty(kod))
            {
                takip = takip.Where(y => y.TakipKodu.Contains(kod));
            }
            return View(takip.ToList());
        }
        [HttpGet]
        public ActionResult YeniKargo()
        {
            Random rdn = new Random();
            string[] karakterler = {"A", "B", "C", "D","E","F","G"};

            int k1 ,k2 ,k3;
            k1 = rdn.Next(0, 7);
            k2 = rdn.Next(0, 7);
            k3 = rdn.Next(0, 7);
            int s1, s2, s3;
            s1 = rdn.Next(100, 999);
            s2 = rdn.Next(10, 99);
            s3 = rdn.Next(10, 99);
            string kod = s1 + karakterler[k1] + s2 + karakterler[k2] + s3 + karakterler[k3];
            ViewBag.takipkod = kod;
            return View();
        }
        [HttpPost]
        public ActionResult YeniKargo(KargoDetay k)
        {
            c.KargoDetays.Add(k);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KargoTakip(string id)
        {
            var detay = c.KargoTakips.Where(x => x.TakipKodu == id).ToList();
            return View(detay);
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Kargo/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<KargoDetay>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Kargolar</h2>

@using (Html.BeginForm("Index", "Kargo", FormMethod.Get))
{
    <p>
        Kargo Takip Numarası : @Html.TextBox("kod")
        <input type="submit" value="Ara" />
    </p>
}

<table class="table table-condensed">
    <tr>
        <th>ID</th>
        <th>TakipKodu</th>
        <th>Personel</th>
        <th>Alıcı</th>
        <th>Tarih</th>
        <th>Detaylar</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.KargoDetayid</td>
            <td>@x.TakipKodu</td>
            <td>@x.Personel</td>
            <td>@x.Alici</td>
            <td>@x.Tarih</td>
            <td><a href="/Kargo/KargoTakip/@x.TakipKodu" class="btn btn-info">Detaylar</a></td>

        </tr>
    }

</table>
<a href="/Kargo/YeniKargo/" class="btn btn-primary">Yeni Kargo Ekle</a>

MvcOnlineTicariOtomasyon/Views/Kargo/KargoTakip.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<KargoTakip>
@{
    ViewBag.Title = "KargoTakip";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>KargoTakip</h2>

<table class="table table-bordered">
    <tr>
        <th>Takip Kodu</th>
        <th>Açıklama</th>
        <th>Tarih</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.TakipKodu</td>
            <td>@x.Aciklama</td>
            <td>@x.TarihZaman</td>
        </tr>
    }

</table>

MvcOnlineTicariOtomasyon/Views/Kargo/YeniKargo.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.KargoDetay
@{
    ViewBag.Title = "YeniKargo";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<h2>YeniKargo</h2>

<form class="form-group" method="post">

    @Html.LabelFor(x => x.TakipKodu)
    <input type="text" value="@ViewBag.takipkod" name="TakipKodu" class="form-control" readonly />
    <br />
    @Html.LabelFor(x => x.Personel)
    @Html.TextBoxFor(x => x.Personel, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Alici)
    @Html.TextBoxFor(x => x.Alici, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Aciklama)
    @Html.TextAreaFor(x => x.Aciklama, 4, 1, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Tarih)
    <input class="form-control" name="Tarih" type="date" />
    <br />
    <button class="btn btn-info">Kargoyu Ekle</button>
</form>