MvcOnlineTicariOtomasyon/Models/Siniflar/Urun.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MvcOnlineTicariOtomasyon.Models.Siniflar
{
    public class Urun
    {
        [Key]
        public int UrunID { get; set; }

        [Column(TypeName="Varchar")]
        [StringLength(30, ErrorMessage = "En fazla 30 karakter giriniz")]
        [Required(ErrorMessage = "Bu alanı boş geçmeyin")]
        public string UrunAd { get; set; }
        [Column(TypeName = "Varchar")]
        [StringLength(30, ErrorMessage = "En fazla 30 karakter giriniz")]
        [Required(ErrorMessage = "Bu alanı boş geçmeyin")]
        public string Marka { get; set; }
        public short Stok { get; set; }
        public decimal AlisFiyat { get; set; }
        public decimal SatisFiyat { get; set; }
        public bool Durum { get; set; }

        [Column(TypeName = "Varchar")]
        [StringLength(250, ErrorMessage = "En fazla 250 karakter giriniz")]
        [Required(ErrorMessage = "Bu alanı boş geçmeyin")]
        public string UrunGorsel { get; set; }

        public int Kategoriid { get; set; }
        public virtual Kategori Kategori { get; set; }
        public ICollection<SatisHareket>  SatisHarekets { get; set; }
    }
}

MvcOnlineTicariOtomasyon/Controllers/UrunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcOnlineTicariOtomasyon.Models.Siniflar;

namespace MvcOnlineTicariOtomasyon.Controllers
{
    public class UrunController : Controller
    {
        // GET: Urun
        Context c = new Context();
        public ActionResult Index(string arama)
        {
            var urunler = from x in c.Uruns select x;
            if (!string.IsNullOrEmpty(arama))
            {
                urunler = urunler.Where(y => y.UrunAd.Contains(arama));
            }
            return View(urunler.ToList());
        }
        [HttpGet]
        public ActionResult YeniUrun()
        {
            List<SelectListItem> deger1 = (from x in c.Kategoris.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.KategoriAd,
                                               Value = x.KategoriID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;

            return View();
        }
        [HttpPost]
        public ActionResult YeniUrun(Urun u)
        {
            c.Uruns.Add(u);
            u.Durum = true;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult UrunSil(int id)
        {
            var sil = c.Uruns.Find(id);
            sil.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult UrunGetir(int id)
        {
            List<SelectListItem> deger1 = (from x in c.Kategoris.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.KategoriAd,
                                               Value = x.KategoriID.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            var urunguncelle = c.Uruns.Find(id);
            return View("UrunGetir", urunguncelle);
        }
        public ActionResult UrunGuncelle(Urun u)
        {
            var urunum= c.Uruns.Find(u.UrunID);
            urunum.UrunAd = u.UrunAd;
            urunum.Marka = u.Marka;
            urunum.Stok = u.Stok;
            urunum.AlisFiyat = u.AlisFiyat;
            urunum.SatisFiyat = u.SatisFiyat;
            urunum.Durum = u.Durum;
            urunum.Kategoriid = u.Kategoriid;
            urunum.UrunGorsel = u.UrunGorsel;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult SatisYap(int id)
        {
            List<SelectListItem> deger2 = (from x in c.Personels.ToList()
                                           select new SelectListItem
                                           {
                                               Text = x.PersonelAd + " " + x.PersonelSoyad,
                                               Value = x.PersonelID.ToString()
                                           }).ToList();
            ViewBag.dgr2 = deger2;

            var deger1 = c.Uruns.Find(id);
            ViewBag.dgr1 = deger1.UrunID;
            ViewBag.dgr3 = deger1.SatisFiyat;

            return View();
        }
        [HttpPost]
        public ActionResult SatisYap(SatisHareket p)
        {
            c.SatisHarekets.Add(p);
            p.Tarih = DateTime.Parse(DateTime.Now.ToShortDateString());
            c.SaveChanges();
            return RedirectToAction("Index","Satis");
        }
    }
}

MvcOnlineTicariOtomasyon/Views/Urun/Index.cshtml
@using MvcOnlineTicariOtomasyon.Models.Siniflar
@model List<Urun>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Ürünlerimiz</h2>
<br />
@using (Html.BeginForm("Index", "Urun", FormMethod.Get))
            {
                <p>
                    Ürün Adı : @Html.TextBox("arama")
                    <input type="submit" value="Ara" />
                </p>
            }

<table class="table table-bordered">
    <tr>
        <th>Ürün ID</th>
        <th>Ürün Adı</th>
        <th>Marka</th>
        <th>Stok</th>
        <th>Alış Fiyatı</th>
        <th>Satış Fiyatı</th>
        <th>Durum</th>
        <th>Kategori</th>
        <th>Görsel</th>
        <th>Güncelle</th>
        <th>Sil</th>
        <th>Detaylar</th>
        <th>Satış Yap</th>
    </tr>
    @foreach (var x in Model)
    {
<tr>
    <td>@x.UrunID</td>
    <td>@x.UrunAd</td>
    <td>@x.Marka</td>
    <td>@x.Stok</td>
    <td>@x.AlisFiyat₺</td>
    <td>@x.SatisFiyat₺</td>
    <td>@x.Durum</td>
    <td>@x.Kategori.KategoriAd</td>
    <td>
        <img src="@x.UrunGorsel" style="width:75px;height:50px;" />
    </td>
    <td><a href="/Urun/UrunGetir/@x.UrunID" class="btn btn-success">Guncelle</a></td>
    <td><a href="/Urun/UrunSil/@x.UrunID" class="btn btn-danger">Sil</a></td>
    <td><a href="/UrunDetay/Index/@x.UrunID" class="btn btn-info">Detaylar</a></td>
    <td><a href="/Urun/SatisYap/@x.UrunID" class="btn btn-default" style="background-color:aqua">Satış Yap</a></td>
</tr>
    }

</table>
<a href="/Urun/YeniUrun/" class="btn btn-primary">Yeni Ürün Ekle</a>

MvcOnlineTicariOtomasyon/Views/Urun/SatisYap.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.SatisHareket

@{
    ViewBag.Title = "SatisYap";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />

<h2>SatisYap</h2>

<br />

<form class="form-group" method="post">
    @Html.LabelFor(x => x.Urunid)
    <input type="text" name="Urunid" value="@ViewBag.dgr1" class="form-control" readonly />
    <br />
    @Html.LabelFor(x => x.Personelid)
    @Html.DropDownListFor(x => x.Personelid, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Cariid)
    @Html.TextBoxFor(x => x.Cariid, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Adet)
    <input type="number" name="Adet" class="form-control" id="txt1" onkeyup="sum();" max="25" min="0" placeholder="Adet giriniz"/>
    <br />
    @Html.LabelFor(x => x.Fiyat)
    <input type="text" name="Urunid" id="txt2" onkeyup="sum();"  value="@ViewBag.dgr3" class="form-control" />
    <br />
    @Html.LabelFor(x => x.ToplamTutar)
    <input type="text" name="ToplamTutar" id="txt3" class="form-control"  />
    <br />
    <button class="btn btn-info">Satış Yap</button>
</form>

<br />

<script>
    function sum() {
        var sayi1 = document.getElementById('txt1').value;
        var sayi2 = document.getElementById('txt2').value;
        var sonuc = parseInt(sayi1) * parseInt(sayi2);
        if (!isNaN(sonuc)) {
            document.getElementById('txt3').value = sonuc;
        }
    }
</script>

MvcOnlineTicariOtomasyon/Views/Urun/UrunGetir.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Urun
@{
    ViewBag.Title = "UrunGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Urun Güncelle</h2>
<br />

@using (Html.BeginForm("UrunGuncelle", "Urun", FormMethod.Post))
{
    @Html.HiddenFor(x=>x.UrunID)
    <br />
    @Html.LabelFor(x => x.UrunAd)
    @Html.TextBoxFor(x => x.UrunAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Marka)
    @Html.TextBoxFor(x => x.Marka, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Stok)
    @Html.TextBoxFor(x => x.Stok, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.AlisFiyat)
    @Html.TextBoxFor(x => x.AlisFiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.SatisFiyat)
    @Html.TextBoxFor(x => x.SatisFiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Durum)
    @Html.TextBoxFor(x => x.Durum, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Kategori)
    @Html.DropDownListFor(x => x.Kategoriid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.UrunGorsel)
    @Html.TextBoxFor(x => x.UrunGorsel, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Ürün Bilgilerini Güncelle</button>
}

MvcOnlineTicariOtomasyon/Views/Urun/YeniUrun.cshtml
@model MvcOnlineTicariOtomasyon.Models.Siniflar.Urun
@{
    ViewBag.Title = "YeniUrun";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Yeni Urun Ekle</h2>
<br />

<form class="form-group" method="post">
    @Html.LabelFor(x => x.UrunAd)
    @Html.TextBoxFor(x => x.UrunAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Marka)
    @Html.TextBoxFor(x => x.Marka, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Stok)
    @Html.TextBoxFor(x => x.Stok, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.AlisFiyat)
    @Html.TextBoxFor(x => x.AlisFiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.SatisFiyat)
    @Html.TextBoxFor(x => x.SatisFiyat, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Kategori)
    @Html.DropDownListFor(x=>x.Kategoriid, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.UrunGorsel)
    @Html.TextBoxFor(x => x.UrunGorsel, new { @class = "form-control" })
    <br />
    <button class="btn btn-info">Ürün Ekle</button>
</form>